### ISSUE TITLE
Hello world fails

### ISSUE THREAD

**Issue by rdebath** [Tresky/brainfuck-interpreter#1]
This should print `Hello World!`

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by Tresky** [comment]
This works for me. You must have tested it out on the tail end of me cleaning up the bugs I was encountering.

**Comment by rdebath** [comment]
Yup, works fine now on Linux, once I fixed the trivial syntax error that is.

Just increasing `CODE_SIZE` for the big stuff doesn't seem to work though... not sure why.

**Comment by Tresky** [comment]
What sort of big stuff are you talking about? The Brainfuck specification dictated a data buffer of 30000 values, so that's why it's set to that.

EDIT: I fixed the syntax error, also. Thanks for pointing that out.

**Comment by rdebath** [comment]
Actually, the "data buffer" or tape _should_ be unbounded, but 30k is probably enough as the only things I know of that go beyond that are [AWIB](https://github.com/matslina/awib) compiling itself and a couple of special tests.

I was actually talking about the program size there's one very nice "little" BF program called [Lost Kingdom](https://github.com/rdebath/LostKingdom/blob/gh-pages/LostKng.b) which is about 2 megabytes of BF code. Then there's the very silly [Brainfuck on Rails](https://github.com/cookjj/Brainfuck-on-Rails) which is 19MB.

PS: [This](https://github.com/ShockSoc/2016-brainfuck-submissions/blob/master/extra_hard_ascii1.bf) banner generating program is also tends to kill some interpreters and many compilers.

**Comment by Tresky** [comment]
Apparently, the standard is non-conforming across multiple sites (which I should expect from an esolang). I just looked at a few more of specifications and some say bounded, others say unbounded. I think you're probably right, though; 30K should be enough at least for normal operation.

As for the size of the code, as it stands right now, I only allow 30K characters for the code as well, but you said you tried increasing the size of the tape. I just attempted to run the Lost King and it works in the beginning for me. After taking input, it begins to fail. Does that sound similar to your experience.

PS: I have just enabled the use of single-line comments by using #. So, the comments in the Lost Kingdom file will be ignored.

**Comment by rdebath** [comment]
Naa, I got segfaults;

... ... ...

Oh, ... remember never ever do this again ...

You `code_pointer` variable (and `pointer`) is a 16bit short. That type is too short for an array index and should only be used if you're trying to save space in large arrays and structures.

**Comment by Tresky** [comment]
This is strange! I get Lost Kingdom to execute when using 16-bit shorts. As soon as I make them 32-bit integers I get seg faults like you.

**Comment by rdebath** [comment]
I'd guess that's because the Mac is limiting the stack space it'll give you in one go. It looks like you have to make stack allocations smaller than about 8Mb at a time.

It's best to allocate stuff over a few kilobytes on the heap using `new`, though in this case the automatic clearing of `calloc` would be nice.

**Comment by Tresky** [comment]
I recently rewrote my local copy of the code to use a vector to dynamically allocate space for the ticker and the code. It has helped in the regards for avoiding segfaults. However, now I'm simply having problems on the input being taken correctly.

I have just pushed the latest code if you want to take a look. You might have an idea as to what's going on with input. I feel like it has something to do with clearing the `cin` buffer, but I feel like I have tried almost everything to clear it properly.

**Comment by rdebath** [comment]
I assume you're still using LostKng.b?
The way it's written it needs the sequence `[-]-` to wrap and it needs `[-]-[-]` to run quickly.
If your limits on the range of the cells are removed it can probably run successfully ... but will take hours to print the next description unless the cell size is reduced to 8bits.

With those changes it works fine.

``` diff
diff --git a/interpreter.cpp b/interpreter.cpp
index a36fc97..70fd24c 100644
--- a/interpreter.cpp
+++ b/interpreter.cpp
@@ -22,7 +22,7 @@ int main(int argc, char* argv[])
   std::vector<char> code;
   int code_pointer = 0;

-  std::vector<int> ticker;
+  std::vector<unsigned char> ticker;
   ticker.push_back(0);

   int pointer = 0;
@@ -58,11 +58,11 @@ int main(int argc, char* argv[])
           --pointer;
         break;
       case '+':
-        if (ticker[pointer] < INT_MAX)
+        //if (ticker[pointer] < INT_MAX)
           ++ticker[pointer];
         break;
       case '-':
-        if (ticker[pointer] > 0)
+        //if (ticker[pointer] > 0)
           --ticker[pointer];
         break;
       case '.':
```

**Comment by Tresky** [comment]
Woah! That did it! I didn't realize that the program takes advantage of wrapping. Thanks for that bit of knowledge.
